[theme]
base = "dark"
primaryColor = "#eb652b"
backgroundColor = "#eb652b"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
port = 8502 # change port number. By default, streamlit used 8501 port.
headless = true # This will eliminate automatically open browser

[browser]
serverAddress = "146.190.57.108" 
serverPort = 8502
